In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Numpy merupakan library python digunakan untuk komputasi matriks
Matplotlib merupakan library python untuk presentasi data berupa grafik atau plot

In [2]:
dataset = pd.read_csv('data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(x)

[['Perancis' 44.0 72000.0]
 ['Spanyol' 27.0 48000.0]
 ['Jerman' 30.0 54000.0]
 ['Spanyol' 38.0 61000.0]
 ['Jerman' 40.0 nan]
 ['Perancis' 35.0 58000.0]
 ['Spanyol' nan 52000.0]
 ['Perancis' 48.0 79000.0]
 ['Jerman' 50.0 83000.0]
 ['Perancis' 37.0 67000.0]]


In [4]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

impute dilakukan untuk mengisi data yang kosong (missing_values), dengan strategy mean atau rata-rata

In [5]:
print(x)

[['Perancis' 44.0 72000.0]
 ['Spanyol' 27.0 48000.0]
 ['Jerman' 30.0 54000.0]
 ['Spanyol' 38.0 61000.0]
 ['Jerman' 40.0 63777.77777777778]
 ['Perancis' 35.0 58000.0]
 ['Spanyol' 38.77777777777778 52000.0]
 ['Perancis' 48.0 79000.0]
 ['Jerman' 50.0 83000.0]
 ['Perancis' 37.0 67000.0]]


In [17]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

Karena ada data non nomerik atau nominal, maka data harus diencode menggunakan OneHotEncoder

In [22]:
print(x)

[[0.0 1.0 0.0 1.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 1.0 0.0 35.0 58000.0]
 [0.0 1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 1.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 1.0 0.0 37.0 67000.0]]


In [18]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [19]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [23]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)


membagi training dan testing menggunakan train_test_split

In [25]:
print(x_train)

[[0.0 1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 1.0 0.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 1.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 1.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 1.0 0.0 35.0 58000.0]]


In [27]:
print(x_test)

[[1.0 0.0 1.0 0.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 1.0 0.0 37.0 67000.0]]


In [26]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [28]:
print(y_test)

[0 1]


In [29]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [30]:
print(x_train)

[[0.0 1.0 0.0 -0.7745966692414834 1.2909944487358056 -0.19159184384578545
  -1.0781259408412425]
 [1.0 0.0 1.0 -0.7745966692414834 -0.7745966692414834
  -0.014117293757057777 -0.07013167641635372]
 [0.0 1.0 0.0 1.2909944487358056 -0.7745966692414834 0.566708506533324
  0.633562432710455]
 [0.0 1.0 0.0 -0.7745966692414834 1.2909944487358056 -0.30453019390224867
  -0.30786617274297867]
 [0.0 1.0 0.0 -0.7745966692414834 1.2909944487358056 -1.9018011447007988
  -1.420463615551582]
 [0.0 1.0 0.0 1.2909944487358056 -0.7745966692414834 1.1475343068237058
  1.232653363453549]
 [1.0 0.0 1.0 -0.7745966692414834 -0.7745966692414834 1.4379472069688968
  1.5749910381638885]
 [0.0 1.0 0.0 1.2909944487358056 -0.7745966692414834 -0.7401495441200351
  -0.5646194287757332]]


In [31]:
print(x_test)

[[1.0 0.0 1.0 -0.7745966692414834 -0.7745966692414834 -1.4661817944830124
  -0.9069571034860727]
 [0.0 1.0 0.0 1.2909944487358056 -0.7745966692414834 -0.44973664397484414
  0.2056403393225306]]
